import type { Talep, Teklif, RozetKod, Kategori } from "./types";

export const ROZET_METIN: Record<RozetKod, { kisa: string; aciklama: string }> = {
  kimlik:   { kisa: "Kimlik doğrulandı",  aciklama: "T.C. kimlik ve telefon doğrulaması tamamlandı." },
  butce:    { kisa: "Bütçe belgelendi",   aciklama: "Banka referans mektubu veya hesap özeti ile bütçe teyit edildi." },
  gecmis:   { kisa: "Geçmiş işlem",       aciklama: "Platform üzerinden daha önce en az bir işlemi tamamladı." },
  hizli:    { kisa: "Hızlı dönüş",        aciklama: "Gelen tekliflere ortalama 4 saat içinde yanıt veriyor." },
  kurumsal: { kisa: "Kurumsal",           aciklama: "Vergi levhası doğrulanmış kurumsal üye." },
  pesin:    { kisa: "Peşin alıcı",        aciklama: "Kredi veya satış şartı olmadan peşin ödeme yapabilir." },
};

export const KATEGORI_METIN: Record<Kategori, { ad: string; tekil: string }> = {
  emlak:  { ad: "Emlak",   tekil: "mülk" },
  vasita: { ad: "Vasıta",  tekil: "araç" },
  deniz:  { ad: "Deniz Araçları", tekil: "tekne" },
};

export const TALEPLER: Talep[] = [
  {
    id: "TLP-4821",
    kategori: "emlak",
    tur: "Villa",
    baslik: "Yalıkavak–Türkbükü hattında denize sıfır, özel havuzlu villa",
    sehir: "Muğla",
    konum: "Bodrum / Yalıkavak, Türkbükü, Gündoğan",
    butceMin: 85_000_000,
    butceMax: 120_000_000,
    paraBirimi: "TRY",
    odeme: "Tamamı peşin",
    kriterler: [
      { etiket: "Kapalı alan", deger: "400 m² ve üzeri", zorunlu: true },
      { etiket: "Arsa", deger: "1.000 m² ve üzeri", zorunlu: true },
      { etiket: "Denize mesafe", deger: "Maksimum 300 m", zorunlu: true },
      { etiket: "Havuz", deger: "Özel havuz şart", zorunlu: true },
      { etiket: "Tapu", deger: "Kat mülkiyetli, iskanlı", zorunlu: true },
      { etiket: "Yapım yılı", deger: "2015 sonrası tercih", zorunlu: false },
      { etiket: "Oda", deger: "5+1 ve üzeri", zorunlu: false },
      { etiket: "Otopark", deger: "Kapalı, 2 araç", zorunlu: false },
    ],
    not: "Site içi kabul edilir ancak aidatın makul olması gerekiyor. Kiralama geçmişi olan mülkler öncelikli. Ekim ayı içinde yerinde görmek üzere Bodrum'da olacağım.",
    rozetler: ["kimlik", "butce", "pesin", "hizli"],
    aciliyet: "acil",
    aciliyetMetin: "Bu ay içinde",
    yayin: "2026-09-26",
    sonGecerlilik: "2026-11-26",
    goruntuleme: 312,
    teklifSayisi: 4,
    izleyen: 9,
    tokenMaliyeti: 5,
    aliciKod: "Alıcı #4821",
    uyum: 94,
  },
  {
    id: "TLP-4805",
    kategori: "emlak",
    tur: "Rezidans Dairesi",
    baslik: "Nişantaşı–Teşvikiye çevresinde 4+1, yüksek tavanlı daire",
    sehir: "İstanbul",
    konum: "Şişli / Nişantaşı, Teşvikiye, Maçka",
    butceMin: 45_000_000,
    butceMax: 62_000_000,
    paraBirimi: "TRY",
    odeme: "%60 peşin + banka kredisi",
    kriterler: [
      { etiket: "Net alan", deger: "220 m² ve üzeri", zorunlu: true },
      { etiket: "Oda", deger: "4+1", zorunlu: true },
      { etiket: "Kat", deger: "3. kat ve üzeri", zorunlu: true },
      { etiket: "Asansör", deger: "Şart", zorunlu: true },
      { etiket: "Otopark", deger: "En az 1 kapalı", zorunlu: true },
      { etiket: "Tavan yüksekliği", deger: "3 m üzeri tercih", zorunlu: false },
      { etiket: "Bina yaşı", deger: "Yeni veya komple restore", zorunlu: false },
    ],
    not: "Ara kat tercih ediyorum, zemin ve bahçe katı düşünmüyorum. Depremsellik raporu olan binalar öncelikli.",
    rozetler: ["kimlik", "butce", "gecmis"],
    aciliyet: "normal",
    aciliyetMetin: "3 ay içinde",
    yayin: "2026-09-22",
    sonGecerlilik: "2026-12-22",
    goruntuleme: 486,
    teklifSayisi: 7,
    izleyen: 14,
    tokenMaliyeti: 4,
    aliciKod: "Alıcı #4805",
    uyum: 88,
  },
  {
    id: "TLP-4790",
    kategori: "emlak",
    tur: "Yalı Dairesi",
    baslik: "Boğaz'da denize cepheli yalı dairesi — Anadolu yakası",
    sehir: "İstanbul",
    konum: "Üsküdar–Beykoz / Kuzguncuk, Çengelköy, Kandilli",
    butceMin: 6_000_000,
    butceMax: 9_500_000,
    paraBirimi: "USD",
    odeme: "Tamamı peşin, döviz",
    kriterler: [
      { etiket: "Cephe", deger: "Doğrudan deniz cephesi", zorunlu: true },
      { etiket: "Net alan", deger: "180 m² ve üzeri", zorunlu: true },
      { etiket: "Tapu", deger: "Kat mülkiyeti, takyidatsız", zorunlu: true },
      { etiket: "Kullanım", deger: "Boş teslim", zorunlu: true },
      { etiket: "İskele", deger: "Ortak iskele hakkı tercih", zorunlu: false },
      { etiket: "Otopark", deger: "Tahsisli yer", zorunlu: false },
    ],
    not: "Yurt dışında yaşıyorum, süreç vekâlet ile yürüyecek. SİT ve tescil durumu net olan mülkler tercih edilir. Anadolu yakası kesin.",
    rozetler: ["kimlik", "butce", "pesin"],
    aciliyet: "normal",
    aciliyetMetin: "6 ay içinde",
    yayin: "2026-09-18",
    sonGecerlilik: "2027-01-18",
    goruntuleme: 731,
    teklifSayisi: 3,
    izleyen: 21,
    tokenMaliyeti: 8,
    aliciKod: "Alıcı #4790",
    uyum: 71,
  },
  {
    id: "TLP-4776",
    kategori: "emlak",
    tur: "Taş Ev / Butik Yatırım",
    baslik: "Alaçatı merkezde butik otele dönüştürülebilir taş ev",
    sehir: "İzmir",
    konum: "Çeşme / Alaçatı merkez, Hacımemiş",
    butceMin: 30_000_000,
    butceMax: 44_000_000,
    paraBirimi: "TRY",
    odeme: "Peşin, gerekirse takasla",
    kriterler: [
      { etiket: "Arsa", deger: "350 m² ve üzeri", zorunlu: true },
      { etiket: "İmar", deger: "Turizm veya konut+ticaret", zorunlu: true },
      { etiket: "Konum", deger: "Yürüme mesafesinde merkez", zorunlu: true },
      { etiket: "Yapı", deger: "Özgün taş doku korunmuş", zorunlu: false },
      { etiket: "Oda potansiyeli", deger: "8–14 oda", zorunlu: false },
    ],
    not: "Ruhsat süreci başlamış projeler ciddi avantaj sağlar. Elimde Alaçatı'da işletmekte olduğum bir tesis var, ikinciyi açıyorum.",
    rozetler: ["kimlik", "butce", "kurumsal", "gecmis"],
    aciliyet: "normal",
    aciliyetMetin: "Sezon öncesi",
    yayin: "2026-09-15",
    sonGecerlilik: "2026-12-15",
    goruntuleme: 402,
    teklifSayisi: 5,
    izleyen: 11,
    tokenMaliyeti: 4,
    aliciKod: "Alıcı #4776",
    uyum: 83,
  },
  {
    id: "TLP-4762",
    kategori: "emlak",
    tur: "Müstakil Ev",
    baslik: "Koru içinde, bahçeli müstakil ev — İstanbul kuzey hattı",
    sehir: "İstanbul",
    konum: "Sarıyer–Beykoz / Zekeriyaköy, Acarkent, Kemerburgaz",
    butceMin: 55_000_000,
    butceMax: 78_000_000,
    paraBirimi: "TRY",
    odeme: "Mevcut konut satışı + peşin",
    kriterler: [
      { etiket: "Kapalı alan", deger: "350 m² ve üzeri", zorunlu: true },
      { etiket: "Bahçe", deger: "500 m² ve üzeri", zorunlu: true },
      { etiket: "Oda", deger: "5+2", zorunlu: true },
      { etiket: "Güvenlik", deger: "7/24 site güvenliği", zorunlu: true },
      { etiket: "Okul", deger: "Özel okula yakınlık", zorunlu: false },
      { etiket: "Isıtma", deger: "Yerden ısıtma", zorunlu: false },
    ],
    not: "Ailece taşınıyoruz, okul dönemine yetişmesi ideal. Mevcut Etiler'deki dairemin satışı paralel yürüyor, o yüzden esnek kapanış tarihi olan satıcılar tercihim.",
    rozetler: ["kimlik", "butce", "hizli"],
    aciliyet: "acil",
    aciliyetMetin: "Bu ay içinde",
    yayin: "2026-09-27",
    sonGecerlilik: "2026-11-27",
    goruntuleme: 198,
    teklifSayisi: 2,
    izleyen: 7,
    tokenMaliyeti: 4,
    aliciKod: "Alıcı #4762",
    uyum: 90,
  },
  {
    id: "TLP-4749",
    kategori: "emlak",
    tur: "Arazi",
    baslik: "Kaş–Kalkan arası deniz manzaralı, imarlı arazi",
    sehir: "Antalya",
    konum: "Kaş / Kalkan, Çukurbağ, İslamlar",
    butceMin: 18_000_000,
    butceMax: 26_000_000,
    paraBirimi: "TRY",
    odeme: "Tamamı peşin",
    kriterler: [
      { etiket: "Yüzölçüm", deger: "2.000 m² ve üzeri", zorunlu: true },
      { etiket: "İmar", deger: "Konut imarlı, TAKS/KAKS net", zorunlu: true },
      { etiket: "Manzara", deger: "Kesintisiz deniz manzarası", zorunlu: true },
      { etiket: "Yol", deger: "Asfalt yol cepheli", zorunlu: true },
      { etiket: "Altyapı", deger: "Elektrik + su mevcut", zorunlu: false },
    ],
    not: "Kendi villamı yaptıracağım, hisseli tapu kesinlikle düşünmüyorum. Zeytinlik vasfı olan yerler ilgimi çekmiyor.",
    rozetler: ["kimlik", "butce", "pesin"],
    aciliyet: "firsat",
    aciliyetMetin: "Doğru fırsat çıkarsa",
    yayin: "2026-09-10",
    sonGecerlilik: "2027-03-10",
    goruntuleme: 264,
    teklifSayisi: 6,
    izleyen: 5,
    tokenMaliyeti: 3,
    aliciKod: "Alıcı #4749",
    uyum: 62,
  },
  {
    id: "TLP-4731",
    kategori: "emlak",
    tur: "Butik Otel",
    baslik: "Çeşme bölgesinde işletmesi devam eden butik otel",
    sehir: "İzmir",
    konum: "Çeşme / Ilıca, Alaçatı, Dalyan",
    butceMin: 4_000_000,
    butceMax: 6_500_000,
    paraBirimi: "EUR",
    odeme: "Peşin + kısmi vadeli",
    kriterler: [
      { etiket: "Oda sayısı", deger: "16–34 oda", zorunlu: true },
      { etiket: "Belge", deger: "Turizm işletme belgeli", zorunlu: true },
      { etiket: "Doluluk", deger: "Son 2 sezon %65 üzeri", zorunlu: true },
      { etiket: "Mülkiyet", deger: "Kendi mülkü (kira değil)", zorunlu: true },
      { etiket: "Havuz", deger: "Mevcut", zorunlu: false },
      { etiket: "Devir", deger: "Personel ile birlikte", zorunlu: false },
    ],
    not: "Finansal tablolar ve doluluk raporları paylaşılabilir olmalı. Gizlilik sözleşmesi karşılığında ciddi görüşme yapılır. Aracısız, doğrudan mal sahibi tercihimdir.",
    rozetler: ["kimlik", "butce", "kurumsal", "gecmis", "pesin"],
    aciliyet: "normal",
    aciliyetMetin: "Sezon kapanışında",
    yayin: "2026-09-08",
    sonGecerlilik: "2027-01-08",
    goruntuleme: 918,
    teklifSayisi: 2,
    izleyen: 28,
    tokenMaliyeti: 10,
    aliciKod: "Alıcı #4731",
    uyum: 77,
  },
  {
    id: "TLP-4718",
    kategori: "emlak",
    tur: "Ofis Katı",
    baslik: "Kiracılı, komple ofis katı — yatırımlık",
    sehir: "İstanbul",
    konum: "Beşiktaş–Sarıyer / Levent, Maslak, Esentepe",
    butceMin: 90_000_000,
    butceMax: 135_000_000,
    paraBirimi: "TRY",
    odeme: "Tamamı peşin, kurumsal",
    kriterler: [
      { etiket: "Kullanım alanı", deger: "800 m² ve üzeri", zorunlu: true },
      { etiket: "Kiracı", deger: "Mevcut ve kurumsal", zorunlu: true },
      { etiket: "Getiri", deger: "Brüt %7 ve üzeri", zorunlu: true },
      { etiket: "Bina", deger: "A sınıfı plaza", zorunlu: true },
      { etiket: "Otopark", deger: "En az 8 araçlık", zorunlu: false },
      { etiket: "Sertifika", deger: "LEED/BREEAM tercih", zorunlu: false },
    ],
    not: "Aile şirketimizin gayrimenkul portföyü için alıyoruz. Kira sözleşmesinin en az 3 yıl daha devam ediyor olması gerekiyor.",
    rozetler: ["kimlik", "butce", "kurumsal", "pesin"],
    aciliyet: "normal",
    aciliyetMetin: "Yıl sonuna kadar",
    yayin: "2026-09-05",
    sonGecerlilik: "2026-12-31",
    goruntuleme: 605,
    teklifSayisi: 4,
    izleyen: 16,
    tokenMaliyeti: 10,
    aliciKod: "Alıcı #4718",
    uyum: 68,
  },
  {
    id: "TLP-4702",
    kategori: "emlak",
    tur: "Villa",
    baslik: "Göcek'te marinaya yakın, iskele hakkı olan villa",
    sehir: "Muğla",
    konum: "Fethiye / Göcek, İnlice",
    butceMin: 3_000_000,
    butceMax: 4_600_000,
    paraBirimi: "EUR",
    odeme: "Tamamı peşin, döviz",
    kriterler: [
      { etiket: "Kapalı alan", deger: "300 m² ve üzeri", zorunlu: true },
      { etiket: "İskele", deger: "İskele veya bağlama hakkı", zorunlu: true },
      { etiket: "Havuz", deger: "Özel havuz", zorunlu: true },
      { etiket: "Marina", deger: "Maksimum 10 dk mesafe", zorunlu: true },
      { etiket: "Arsa", deger: "800 m² ve üzeri", zorunlu: false },
    ],
    not: "Teknem Göcek'te bağlı, o yüzden bölge dışına çıkmıyorum. Kışın kullanılabilir, ısıtması olan bir yapı arıyorum.",
    rozetler: ["kimlik", "butce", "pesin", "hizli"],
    aciliyet: "normal",
    aciliyetMetin: "3 ay içinde",
    yayin: "2026-09-20",
    sonGecerlilik: "2026-12-20",
    goruntuleme: 377,
    teklifSayisi: 3,
    izleyen: 12,
    tokenMaliyeti: 6,
    aliciKod: "Alıcı #4702",
    uyum: 85,
  },
  {
    id: "TLP-4698",
    kategori: "vasita",
    tur: "Otomobil",
    baslik: "Porsche 911 GT3 (992) — Türkiye çıkışlı, hasarsız",
    sehir: "İstanbul",
    konum: "İstanbul, Ankara, İzmir (nakliye dahil değerlendirilir)",
    butceMin: 18_000_000,
    butceMax: 24_500_000,
    paraBirimi: "TRY",
    odeme: "Tamamı peşin",
    kriterler: [
      { etiket: "Model yılı", deger: "2021 ve üzeri", zorunlu: true },
      { etiket: "Kilometre", deger: "Maksimum 20.000 km", zorunlu: true },
      { etiket: "Hasar kaydı", deger: "Kayıtsız, boyasız", zorunlu: true },
      { etiket: "Menşei", deger: "Türkiye çıkışlı", zorunlu: true },
      { etiket: "Servis", deger: "Yetkili servis bakımlı", zorunlu: true },
      { etiket: "Şanzıman", deger: "PDK tercih", zorunlu: false },
      { etiket: "Paket", deger: "Clubsport / seramik fren artı", zorunlu: false },
    ],
    not: "Ekspertize kendi anlaşmalı olduğum yerde girmesi şartıyla ilerliyorum. Yurt dışı çıkışlı ve ağır modifiyeli araçlar ilgi alanımda değil.",
    rozetler: ["kimlik", "butce", "pesin", "gecmis"],
    aciliyet: "acil",
    aciliyetMetin: "2 hafta içinde",
    yayin: "2026-09-25",
    sonGecerlilik: "2026-10-25",
    goruntuleme: 543,
    teklifSayisi: 8,
    izleyen: 19,
    tokenMaliyeti: 3,
    aliciKod: "Alıcı #4698",
    uyum: 91,
  },
  {
    id: "TLP-4684",
    kategori: "vasita",
    tur: "Klasik Otomobil",
    baslik: "Mercedes-Benz 280 SL Pagoda — orijinal veya nitelikli restore",
    sehir: "İstanbul",
    konum: "Türkiye geneli, Avrupa'dan ithal de değerlendirilir",
    butceMin: 180_000,
    butceMax: 270_000,
    paraBirimi: "EUR",
    odeme: "Tamamı peşin, döviz",
    kriterler: [
      { etiket: "Model yılı", deger: "1967–1971", zorunlu: true },
      { etiket: "Orijinallik", deger: "Numara uyumlu motor", zorunlu: true },
      { etiket: "Belge", deger: "Geçmiş dosyası eksiksiz", zorunlu: true },
      { etiket: "Gövde", deger: "Pas ve kaynak geçmişi temiz", zorunlu: true },
      { etiket: "Donanım", deger: "Hardtop dahil", zorunlu: false },
      { etiket: "Renk", deger: "Orijinal renk tercih", zorunlu: false },
    ],
    not: "Koleksiyonuma katacağım, kullanım amaçlı değil. Bağımsız uzman raporu şart. Acelem yok ama doğru araç çıkarsa aynı hafta kapanır.",
    rozetler: ["kimlik", "butce", "pesin", "gecmis"],
    aciliyet: "firsat",
    aciliyetMetin: "Doğru araç çıkarsa",
    yayin: "2026-08-30",
    sonGecerlilik: "2027-02-28",
    goruntuleme: 289,
    teklifSayisi: 2,
    izleyen: 8,
    tokenMaliyeti: 4,
    aliciKod: "Alıcı #4684",
    uyum: 58,
  },
  {
    id: "TLP-4671",
    kategori: "vasita",
    tur: "SUV",
    baslik: "Range Rover Autobiography — 2024 ve üzeri, düşük km",
    sehir: "Ankara",
    konum: "Ankara, İstanbul",
    butceMin: 12_000_000,
    butceMax: 16_500_000,
    paraBirimi: "TRY",
    odeme: "Takas + peşin",
    kriterler: [
      { etiket: "Model yılı", deger: "2024 ve üzeri", zorunlu: true },
      { etiket: "Kilometre", deger: "Maksimum 25.000 km", zorunlu: true },
      { etiket: "Donanım", deger: "Autobiography / LWB", zorunlu: true },
      { etiket: "Hasar kaydı", deger: "Ağır hasar kaydı olmayacak", zorunlu: true },
      { etiket: "Garanti", deger: "Devam eden garanti tercih", zorunlu: false },
    ],
    not: "Mevcut 2022 model Cayenne'i takasa verebilirim, ekspertiz raporu hazır. Kurumsal fatura kesilebilmesi önemli.",
    rozetler: ["kimlik", "butce", "kurumsal"],
    aciliyet: "normal",
    aciliyetMetin: "1 ay içinde",
    yayin: "2026-09-19",
    sonGecerlilik: "2026-11-19",
    goruntuleme: 421,
    teklifSayisi: 6,
    izleyen: 13,
    tokenMaliyeti: 3,
    aliciKod: "Alıcı #4671",
    uyum: 79,
  },
  {
    id: "TLP-4655",
    kategori: "vasita",
    tur: "Süper Spor",
    baslik: "Ferrari 296 GTB veya McLaren 750S — düşük km, TR çıkışlı",
    sehir: "İstanbul",
    konum: "İstanbul",
    butceMin: 30_000_000,
    butceMax: 42_000_000,
    paraBirimi: "TRY",
    odeme: "Tamamı peşin",
    kriterler: [
      { etiket: "Model yılı", deger: "2023 ve üzeri", zorunlu: true },
      { etiket: "Kilometre", deger: "Maksimum 10.000 km", zorunlu: true },
      { etiket: "Hasar kaydı", deger: "Kayıtsız", zorunlu: true },
      { etiket: "Menşei", deger: "Türkiye çıkışlı, ilk el tercih", zorunlu: true },
      { etiket: "Renk", deger: "Klasik renkler tercih", zorunlu: false },
      { etiket: "Donanım", deger: "Karbon paket / lift sistemi", zorunlu: false },
    ],
    not: "Marka konusunda esneğim, belirleyici olan araç geçmişi ve orijinalliği. Trackday geçmişi olan araçlar elenir.",
    rozetler: ["kimlik", "butce", "pesin", "hizli", "gecmis"],
    aciliyet: "normal",
    aciliyetMetin: "2 ay içinde",
    yayin: "2026-09-12",
    sonGecerlilik: "2026-12-12",
    goruntuleme: 837,
    teklifSayisi: 5,
    izleyen: 24,
    tokenMaliyeti: 6,
    aliciKod: "Alıcı #4655",
    uyum: 86,
  },
  {
    id: "TLP-4640",
    kategori: "vasita",
    tur: "SUV",
    baslik: "Mercedes-AMG G63 — 2023 ve üzeri, Manufaktur tercih",
    sehir: "İzmir",
    konum: "İzmir, İstanbul, Bursa",
    butceMin: 14_000_000,
    butceMax: 19_000_000,
    paraBirimi: "TRY",
    odeme: "Peşin",
    kriterler: [
      { etiket: "Model yılı", deger: "2023 ve üzeri", zorunlu: true },
      { etiket: "Kilometre", deger: "Maksimum 30.000 km", zorunlu: true },
      { etiket: "Hasar kaydı", deger: "Kayıtsız, boyasız", zorunlu: true },
      { etiket: "Donanım", deger: "Manufaktur paket tercih", zorunlu: false },
      { etiket: "Renk", deger: "Mat renk düşünmüyorum", zorunlu: false },
    ],
    not: "Aracın ekspertiz ve tramer dökümünü ilk görüşmede görmek istiyorum. Kurumsal kiralama geçmişi olan araçlar ilgilendirmiyor.",
    rozetler: ["kimlik", "butce", "pesin"],
    aciliyet: "normal",
    aciliyetMetin: "6 hafta içinde",
    yayin: "2026-09-16",
    sonGecerlilik: "2026-11-16",
    goruntuleme: 356,
    teklifSayisi: 4,
    izleyen: 10,
    tokenMaliyeti: 3,
    aliciKod: "Alıcı #4640",
    uyum: 74,
  },
  {
    id: "TLP-4622",
    kategori: "deniz",
    tur: "Motoryat",
    baslik: "24–30 m motoryat — Ege'de bağlı, charter geçmişi olan",
    sehir: "Muğla",
    konum: "Bodrum, Göcek, Marmaris",
    butceMin: 2_500_000,
    butceMax: 4_200_000,
    paraBirimi: "EUR",
    odeme: "Peşin + kısmi finansman",
    kriterler: [
      { etiket: "Boy", deger: "24–30 m", zorunlu: true },
      { etiket: "Yapım yılı", deger: "2016 ve üzeri", zorunlu: true },
      { etiket: "Kabin", deger: "En az 4 misafir kabini", zorunlu: true },
      { etiket: "Bayrak", deger: "TR veya AB bayraklı", zorunlu: true },
      { etiket: "Charter", deger: "Belgeli charter geçmişi", zorunlu: false },
      { etiket: "Motor saati", deger: "3.000 saat altı", zorunlu: false },
    ],
    not: "Charter işletmeciliği yapacağım, mevcut rezervasyon portföyü olan tekneler öncelikli. Survey masrafı bana ait.",
    rozetler: ["kimlik", "butce", "kurumsal"],
    aciliyet: "firsat",
    aciliyetMetin: "Sezon öncesi",
    yayin: "2026-09-02",
    sonGecerlilik: "2027-02-02",
    goruntuleme: 512,
    teklifSayisi: 1,
    izleyen: 15,
    tokenMaliyeti: 8,
    aliciKod: "Alıcı #4622",
    uyum: 55,
  },
];

export const TEKLIFLER: Teklif[] = [
  {
    id: "TKL-9014",
    talepId: "TLP-4821",
    saticiKod: "Portföy #217",
    saticiTip: "kurumsal",
    saticiRozetler: ["Kurumsal üye", "42 işlem", "Ortalama 2 sa dönüş"],
    saticiIsim: "Ege Kıyı Gayrimenkul — Cem Y.",
    saticiTelefon: "+90 5•• ••• 41 08",
    baslik: "Türkbükü'nde denize 180 m, 520 m² villa — 2019 yapım",
    fiyat: 98_000_000,
    paraBirimi: "TRY",
    konum: "Bodrum / Türkbükü",
    ozellikler: ["520 m² kapalı", "1.350 m² arsa", "6+2", "Özel havuz", "Kat mülkiyetli", "Kapalı otopark 3 araç"],
    mesaj:
      "Talebinizdeki tüm zorunlu kriterleri karşılıyor. Mülk halen kayıtlı bir ilanda yayınlanmıyor, sahibi gizlilik istiyor. 2019 yapım, tadilat gerektirmez. Son 3 yıldır sezonluk kiraya veriliyor, getiri belgeleri mevcut. Hafta içi herhangi bir gün yerinde gezebiliriz.",
    fotoAdet: 24,
    uyum: 96,
    tarih: "2026-09-27",
    durum: "acildi",
  },
  {
    id: "TKL-9008",
    talepId: "TLP-4821",
    saticiKod: "Portföy #064",
    saticiTip: "kurumsal",
    saticiRozetler: ["Kurumsal üye", "19 işlem", "Ortalama 5 sa dönüş"],
    baslik: "Yalıkavak Geriş mevkii, denize sıfır 440 m² villa",
    fiyat: 112_000_000,
    paraBirimi: "TRY",
    konum: "Bodrum / Yalıkavak",
    ozellikler: ["440 m² kapalı", "1.100 m² arsa", "5+1", "Sonsuzluk havuzu", "İskele hakkı", "2021 yapım"],
    mesaj:
      "Denize sıfır, kendi plaj alanı var. Site içinde değil, tamamen müstakil konumda. Sahibi yurt dışına yerleşiyor, bu nedenle satış gündemde. Fiyatta bir miktar esneklik olabilir ancak ciddi alıcı görmek istiyor.",
    fotoAdet: 31,
    uyum: 92,
    tarih: "2026-09-27",
    durum: "yeni",
  },
  {
    id: "TKL-9003",
    talepId: "TLP-4821",
    saticiKod: "Portföy #338",
    saticiTip: "bireysel",
    saticiRozetler: ["Kimlik doğrulandı", "Mülk sahibi"],
    baslik: "Gündoğan koyunda, 400 m² bahçe içinde villa",
    fiyat: 87_500_000,
    paraBirimi: "TRY",
    konum: "Bodrum / Gündoğan",
    ozellikler: ["400 m² kapalı", "980 m² arsa", "5+1", "Özel havuz", "Denize 260 m", "2016 yapım"],
    mesaj:
      "Kendi evim, aracısız satıyorum. Denize yürüme mesafesinde, koy manzaralı. İskan ve kat mülkiyeti tamam. Ekim ayında Bodrum'da olacağınızı belirtmişsiniz, uygun bir günde ben de orada olabilirim.",
    fotoAdet: 18,
    uyum: 89,
    tarih: "2026-09-26",
    durum: "incelendi",
  },
  {
    id: "TKL-8997",
    talepId: "TLP-4821",
    saticiKod: "Portföy #451",
    saticiTip: "kurumsal",
    saticiRozetler: ["Kurumsal üye", "7 işlem"],
    baslik: "Torba mevkii, havuzlu 380 m² villa",
    fiyat: 74_000_000,
    paraBirimi: "TRY",
    konum: "Bodrum / Torba",
    ozellikler: ["380 m² kapalı", "700 m² arsa", "4+1", "Özel havuz", "Denize 600 m"],
    mesaj: "Bütçenizin altında kalan bir alternatif. Denize mesafe kriterinizin biraz dışında ancak fiyat/performans olarak değerlendirmenizi öneririm.",
    fotoAdet: 12,
    uyum: 64,
    tarih: "2026-09-26",
    durum: "reddedildi",
  },
  {
    id: "TKL-8981",
    talepId: "TLP-4698",
    saticiKod: "Portföy #129",
    saticiTip: "kurumsal",
    saticiRozetler: ["Kurumsal üye", "88 işlem", "Ortalama 1 sa dönüş"],
    baslik: "2022 Porsche 911 GT3 — 11.400 km, Türkiye çıkışlı",
    fiyat: 21_750_000,
    paraBirimi: "TRY",
    konum: "İstanbul / Ataşehir",
    ozellikler: ["11.400 km", "PDK", "Seramik fren", "Hasar kaydı yok", "Yetkili servis bakımlı", "İlk el"],
    mesaj:
      "Araç galerimizde mevcut, ilk sahibinden alındı. Tüm bakımları Porsche yetkili serviste yapıldı, dosyası eksiksiz. İstediğiniz ekspertize göndermekte sakınca yok. Takas değerlendirilmez, peşin satış.",
    fotoAdet: 42,
    uyum: 97,
    tarih: "2026-09-26",
    durum: "yeni",
  },
  {
    id: "TKL-8975",
    talepId: "TLP-4698",
    saticiKod: "Portföy #302",
    saticiTip: "bireysel",
    saticiRozetler: ["Kimlik doğrulandı", "Araç sahibi"],
    baslik: "2021 Porsche 911 GT3 Touring — 8.200 km",
    fiyat: 19_400_000,
    paraBirimi: "TRY",
    konum: "İstanbul / Beykoz",
    ozellikler: ["8.200 km", "Touring paket", "Manuel", "Hasar kaydı yok", "Garajda saklandı"],
    mesaj:
      "Kendi aracım, koleksiyonumu daraltıyorum. Touring paket ve manuel şanzıman — PDK tercihinizin dışında ancak orijinalliği ve kilometresi çok iyi. İlgilenirseniz detaylı konuşalım.",
    fotoAdet: 27,
    uyum: 81,
    tarih: "2026-09-25",
    durum: "incelendi",
  },
];

export function talepBul(id: string): Talep | undefined {
  return TALEPLER.find((t) => t.id === id);
}
export function talepTeklifleri(talepId: string): Teklif[] {
  return TEKLIFLER.filter((t) => t.talepId === talepId);
}

export const SEHIRLER = Array.from(new Set(TALEPLER.map((t) => t.sehir))).sort((a, b) =>
  a.localeCompare(b, "tr")
);
export const TURLER = Array.from(new Set(TALEPLER.map((t) => t.tur))).sort((a, b) =>
  a.localeCompare(b, "tr")
);

/** Demo kullanıcı — satıcı tarafı */
export const SATICI = {
  ad: "Cem Yıldırım",
  kurum: "Ege Kıyı Gayrimenkul",
  kod: "Portföy #217",
  token: 34,
  kurumsal: true,
  acilanTalep: 12,
  verilenTeklif: 9,
  gorusmeyeDonen: 5,
  tamamlanan: 2,
  iadeEdilen: 3,
};

/** Demo kullanıcı — alıcı tarafı */
export const ALICI = {
  kod: "Alıcı #4821",
  aktifTalep: 2,
  gelenTeklif: 6,
  okunmamis: 2,
};
